#!/usr/bin/env python

import requests
import argparse

print('here')

parser = argparse.ArgumentParser(
    description='Transfer ReadsPerGene.out.tab files generated by STAR to DMAC Olympus server.'
)

parser.add_argument('--file',
                       type=str,
                       help='input photo')

parser.add_argument('--type',
                       type=str,
                       help='root or leaf')

parser.add_argument('--model',
                       type=str,
                       help='model file')


args = parser.parse_args()
print(args)

# data = {
#     'rename': args.rename,
#     'path': args.path,
#     'token': args.token
# }


# response = requests.post('https://demeter.pharmacy.arizona.edu/api/file-transfer/', files=file_dict, data=data)
# print(str(response.text))